### ISSUE TITLE
设置界面卡顿

### ISSUE THREAD

**Issue by GalliumWang** [GalliumWang/standardSitting#3]
从主界面切换到设置tab时运行产生明显卡顿
可能由线程问题导致

**Comment by huillll** [comment]
RESTART: D:\git_test\standardSitting-master\standardSitting-master\src\main\python\main.py
Traceback (most recent call last):
File "D:\git_test\standardSitting-master\standardSitting-master\src\main\python\main.py", line 592, in
appctxt = ApplicationContext()
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\fbs_runtime\application_context_init_.py", line 31, in init
self.app
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\fbs_runtime\application_context_init_.py", line 54, in app
result.setApplicationName(self.build_settings['app_name'])
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\fbs_runtime\application_context_init_.py", line 65, in build_settings
return _source.load_build_settings(self._project_dir)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\fbs_runtime_source.py", line 37, in load_build_settings
return filter_public_settings(all_settings)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\fbs_runtime_fbs.py", line 27, in filter_public_settings
return {k: settings[k] for k in settings['public_settings']}
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\fbs_runtime_fbs.py", line 27, in
return {k: settings[k] for k in settings['public_settings']}
KeyError: 'app_name'

这个错误怎么解决啊
